# Project
version=1.0.0
group=com.example.exampleaddon

# Mod options
mod_name=Example Addon
mod_author=Example
mod_id=exampleaddon
description=An example addon for the Mineraculous mod
license=All Rights Reserved
icon=icon.png
java_version=21

# Game versions
minecraft_version=1.21.1
next_minecraft_version=1.21.2
mdg_version=2.0.141
neoforge_version=21.1.235
major_fml_version=4

# Parchment
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Required Dependencies
tommylib_version=33.0.2
mineraculous_version=1.0.0-beta10-b

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
